name: Update Documentation

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs

    - name: Build documentation
      run: mkdocs build

    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DOC_SERVER_HOST }}
        username: ${{ secrets.DOC_SERVER_USERNAME }}
        key: ${{ secrets.DOC_SERVER_SSH_KEY }}
        source: "docs/build/"
        target: "/var/www/docs.prancer.io/public_html/web/"
        strip_components: 2

    - name: Run commands on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DOC_SERVER_HOST }}
        username: ${{ secrets.DOC_SERVER_USERNAME }}
        key: ${{ secrets.DOC_SERVER_SSH_KEY }}
        script: |
          cd /var/www/docs.prancer.io/public_html
          # add the commands to update the files here
          find -user azureuser -exec chmod g+w {} \;
