name: Snyk docker scan
on:
  #push:
  workflow_dispatch:
  
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: install Snyk CLI
        run: npm install -g snyk
      - name: Pulling the docker image
        run: docker pull python:3.6-alpine3.10
      - name: run Snyk Code Test
        run:  snyk auth ${{ secrets.SNYK_TOKEN }} && snyk test --docker python --file=dockerfiles/Dockerfile --severity-threshold=high
